name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build Teemo 💖
        run: |
          npm ci
          npm run format
          npm run build --if-present
      - name: Upload build folder (Chrome Extension)
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
          retention-days: 7
