name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Build Teemo 💖
        run: npm ci && npm run build
      - name: Upload build folder (Chrome Extension)
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
          retention-days: 7
